# Use the official Python image from the Docker Hub
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the client code
COPY client.py .

# Command to run the client
CMD ["python3", "client.py", "answer", "--signaling", "tcp-socket", "--signaling-host", "server-service", "--signaling-port", "1234"]
